logging:
  config: classpath:logback-spring-local.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
swagger:
  show: 1
  basePackage: com.sziov
  gitUrl: http://192.168.0.89/gac-nev-monitor-center/nev-monitor-center.git
spark:
  javaHome: C:\Program Files\Java\jdk1.8.0_161
  sparkHome: C:\worksoft\spark-2.3.3-bin-hadoop2.6
  business:
    exportSign:
      jarPath:  C:\worksoft\git\company\gac-nev-monitor-center\bigdata\exporting-historical-data\target\exporting-historical-data-1.0.0.jar
      mainClass: com.sziov.SparkApplication
      master: local
      deployMode:
      appName: exportSign
      queue: exportSign
      driverMemory: 2g
      executorMemory: 2g
      kryoserializerBufferMax: 2500
